name: Windows (Direct3D 11)

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Dependencies
        run: |
          git submodule update --init --recursive
          cd armorcore/v8/libraries/win32/release/
          7z e v8_monolith.7z

      - name: Apply patches
        run: |
          cd armorcore/
          git apply patch/window_handling.diff --directory=Kinc

      - name: Build
        run: |
          node armorcore/make -g direct3d11
          cd armorcore/
          node Kinc/make -g direct3d11 --compile

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Krom
          path: |
            armorcore/Deployment/Krom.exe
            build/krom
